package com.fitnexus.server.enums;

public enum BusinessProfileRevenueType {
    SESSION, PHYSICAL_SESSION, INSTRUCTOR_PACKAGE, MEMBERSHIP_PHYSICAL_CLASS, MEMBERSHIP_GYM, MEMBERSHIP_GYM_DAY_PASS, MEMBERSHIP_ONLINE_CLASS
}
