package com.fitnexus.server.enums;

public enum RecipientFetchType {
    BUSINESS, GYM, FITNESS_CLASS, ONLINE_GROUP_CLASS, ONLINE_ONE_TO_ONE, PERSONAL_COACHING, ONLINE_CLASS_MEMBERSHIP, PHYSICAL_CLASS_MEMBERSHIP
}
